name: training_final
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  gap: ^3.0.1
  flutter_bloc: ^9.1.1
  dio: ^5.9.2
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.14.1


flutter:

  
  uses-material-design: true
  assets:
    - assets/images/
  
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true